import { LocationType } from "@/types";

export const locationsData: LocationType[] = [
  {
    from: "Nigeria",
    to: "Saudi Arabia",
    priceRange: { start: 5_000_000, end: 104_000_000 },
    requirements: [
      "Valid passport",
      "Work visa",
      "Medical clearance certificate",
      "Proof of employment",
    ],
    purpose: "Employment",
  },
  {
    from: "India",
    to: "United States",
    priceRange: { start: 1_500_000, end: 3_000_000 },
    requirements: [
      "H-1B visa approval",
      "Job offer letter",
      "Educational certificates",
      "Passport-sized photographs",
    ],
    purpose: "Employment",
  },
  {
    from: "Canada",
    to: "Australia",
    priceRange: { start: 2_000_000, end: 4_000_000 },
    requirements: [
      "Valid passport",
      "Australian visa",
      "Proof of funds",
      "Travel insurance",
    ],
    purpose: "Tourism",
  },
  {
    from: "Brazil",
    to: "Portugal",
    priceRange: { start: 1_000_000, end: 2_500_000 },
    requirements: [
      "Schengen visa",
      "Round-trip ticket",
      "Proof of accommodation",
      "Travel itinerary",
    ],
    purpose: "Tourism",
  },
  {
    from: "United Kingdom",
    to: "Spain",
    priceRange: { start: 500_000, end: 1_000_000 },
    requirements: [
      "Valid passport",
      "Travel insurance",
      "Proof of accommodation",
      "Return ticket",
    ],
    purpose: "Tourism",
  },
  {
    from: "China",
    to: "Germany",
    priceRange: { start: 2_500_000, end: 5_000_000 },
    requirements: [
      "Schengen visa",
      "Proof of accommodation",
      "Travel insurance",
      "Financial means",
    ],
    purpose: "Business",
  },

  {
    from: "Nigeria",
    to: "Saudi Arabia",
    priceRange: { start: 5_000_000, end: 10_000_000 },
    requirements: [
      "Valid passport",
      "Work visa",
      "Medical clearance certificate",
      "Proof of employment",
    ],
    purpose: "Employment",
  },
  {
    from: "India",
    to: "United States",
    priceRange: { start: 1_500_000, end: 3_000_000 },
    requirements: [
      "H-1B visa approval",
      "Job offer letter",
      "Educational certificates",
      "Passport-sized photographs",
    ],
    purpose: "Employment",
  },
  {
    from: "Canada",
    to: "Australia",
    priceRange: { start: 2_000_000, end: 4_000_000 },
    requirements: [
      "Valid passport",
      "Australian visa",
      "Proof of funds",
      "Travel insurance",
    ],
    purpose: "Tourism",
  },
  {
    from: "Brazil",
    to: "Portugal",
    priceRange: { start: 1_000_000, end: 2_500_000 },
    requirements: [
      "Schengen visa",
      "Round-trip ticket",
      "Proof of accommodation",
      "Travel itinerary",
    ],
    purpose: "Tourism",
  },
  {
    from: "United Kingdom",
    to: "Spain",
    priceRange: { start: 500_000, end: 1_000_000 },
    requirements: [
      "Valid passport",
      "Travel insurance",
      "Proof of accommodation",
      "Return ticket",
    ],
    purpose: "Tourism",
  },
  {
    from: "China",
    to: "Germany",
    priceRange: { start: 2_500_000, end: 5_000_000 },
    requirements: [
      "Schengen visa",
      "Proof of accommodation",
      "Travel insurance",
      "Financial means",
    ],
    purpose: "Business",
  },
  {
    from: "South Africa",
    to: "United Kingdom",
    priceRange: { start: 3_000_000, end: 6_000_000 },
    requirements: [
      "UK visa",
      "Proof of accommodation",
      "Return ticket",
      "Bank statements",
    ],
    purpose: "Tourism",
  },
  {
    from: "Japan",
    to: "France",
    priceRange: { start: 2_000_000, end: 4_500_000 },
    requirements: [
      "Schengen visa",
      "Hotel reservations",
      "Travel itinerary",
      "Travel insurance",
    ],
    purpose: "Tourism",
  },
  {
    from: "Russia",
    to: "Turkey",
    priceRange: { start: 1_000_000, end: 2_000_000 },
    requirements: [
      "E-visa",
      "Valid passport",
      "Proof of accommodation",
      "Return ticket",
    ],
    purpose: "Tourism",
  },
  {
    from: "Mexico",
    to: "Canada",
    priceRange: { start: 1_200_000, end: 2_500_000 },
    requirements: [
      "ETA (Electronic Travel Authorization)",
      "Valid passport",
      "Proof of funds",
      "Travel insurance",
    ],
    purpose: "Tourism",
  },
  {
    from: "Argentina",
    to: "Italy",
    priceRange: { start: 1_500_000, end: 3_000_000 },
    requirements: [
      "Schengen visa",
      "Valid passport",
      "Proof of accommodation",
      "Travel itinerary",
    ],
    purpose: "Tourism",
  },
  {
    from: "Egypt",
    to: "United Arab Emirates",
    priceRange: { start: 700_000, end: 1_500_000 },
    requirements: [
      "UAE visa",
      "Valid passport",
      "Proof of accommodation",
      "Return ticket",
    ],
    purpose: "Business",
  },
];
